### PR TITLE
ENH: Add some disposition for Maintainers of LTS versions

### PR DESCRIPTION
**Pull request by oesteban**

### CODE REVIEW

**Comment by oesteban** [comment]
cc/ @pbellec @ltetrel

**Comment by pbellec** [comment]
heads up: both Basile and Loic are on vacation for the next two weeks. 
They will get to this PR when they are back early September.

**Comment by oesteban** [comment]
There's no rush - this will be dealt with by the governance task-force, so please take it as a FYI (and of course feel invited to participate as soon as you are available!)

**Comment by oesteban** [comment]
Okay, I think it would be best to have this integrated asap, so people read the most complete possible draft next time around. Merging...

**Pull request merged**
